"""m3 candidate_jobs and stage_transitions

Revision ID: 75afa9bfaebf
Revises: 3ff08e5c873b
Create Date: 2026-04-28 11:51:42.608276+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '75afa9bfaebf'
down_revision: str | None = '3ff08e5c873b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('current_stage_id', sa.Integer(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_stage_id'], ['job_stages.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'job_id', name='uq_candidate_job')
    )
    op.create_index(op.f('ix_candidate_jobs_candidate_id'), 'candidate_jobs', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_jobs_job_id'), 'candidate_jobs', ['job_id'], unique=False)
    op.create_table('stage_transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('from_stage_id', sa.Integer(), nullable=True),
    sa.Column('to_stage_id', sa.Integer(), nullable=True),
    sa.Column('by_user', sa.Integer(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['by_user'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_stage_id'], ['job_stages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_stage_id'], ['job_stages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_transitions_candidate_id'), 'stage_transitions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_stage_transitions_job_id'), 'stage_transitions', ['job_id'], unique=False)
    op.add_column('notes', sa.Column('candidate_job_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_notes_candidate_job_id'), 'notes', ['candidate_job_id'], unique=False)
    op.create_foreign_key('fk_notes_candidate_job_id', 'notes', 'candidate_jobs', ['candidate_job_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_notes_candidate_job_id', 'notes', type_='foreignkey')
    op.drop_index(op.f('ix_notes_candidate_job_id'), table_name='notes')
    op.drop_column('notes', 'candidate_job_id')
    op.drop_index(op.f('ix_stage_transitions_job_id'), table_name='stage_transitions')
    op.drop_index(op.f('ix_stage_transitions_candidate_id'), table_name='stage_transitions')
    op.drop_table('stage_transitions')
    op.drop_index(op.f('ix_candidate_jobs_job_id'), table_name='candidate_jobs')
    op.drop_index(op.f('ix_candidate_jobs_candidate_id'), table_name='candidate_jobs')
    op.drop_table('candidate_jobs')
    # ### end Alembic commands ###
